name: Sven337
description: Computers, electronics, politics
markdown: kramdown
kramdown:
    input: GFM
    use_coderay: true
    coderay_defaultlang: C
highlighter: pygments
baseurl: /~sven337
encoding: ISO-8859-15
url: http://perso.aquilenet.fr/~sven337
slideshow:
    width: 300
    height: 300
